/**
 * Wallet
 * Integrate Neem Wallet APIs into your ecosystem to provide your customer the ability to create wallets, set up a financial PIN, ability to manage their wallets and have on request visibility over their balances.
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Wallet);
  }
}(this, function(expect, Wallet) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Wallet.WalletServicesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WalletServicesApi', function() {
    describe('accountLookup', function() {
      it('should call accountLookup successfully', function(done) {
        //uncomment below and update the code to test accountLookup
        //instance.accountLookup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accountUpgrade', function() {
      it('should call accountUpgrade successfully', function(done) {
        //uncomment below and update the code to test accountUpgrade
        //instance.accountUpgrade(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1WalletsValidateOtpPost', function() {
      it('should call apiV1WalletsValidateOtpPost successfully', function(done) {
        //uncomment below and update the code to test apiV1WalletsValidateOtpPost
        //instance.apiV1WalletsValidateOtpPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('balanceInquiry', function() {
      it('should call balanceInquiry successfully', function(done) {
        //uncomment below and update the code to test balanceInquiry
        //instance.balanceInquiry(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('changeMpin', function() {
      it('should call changeMpin successfully', function(done) {
        //uncomment below and update the code to test changeMpin
        //instance.changeMpin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('initiateOtp', function() {
      it('should call initiateOtp successfully', function(done) {
        //uncomment below and update the code to test initiateOtp
        //instance.initiateOtp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('transactionHistory', function() {
      it('should call transactionHistory successfully', function(done) {
        //uncomment below and update the code to test transactionHistory
        //instance.transactionHistory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
